### ISSUE TITLE
does anyyone know how to fix this error

### ISSUE THREAD

**Issue by cypherpunks132** [LeadKiller/ssr-patch#3]
[Steam] SteamApps() Is NULL

**Comment by LeadKiller** [comment]
Hi! Sorry for not replying, I didn't see this issue for some reason.

If you're still having this issue, have you tried these?:
 - Is Garry's Mod 12 launched with `-game garrysmod -steam`?
 - Is Steam running while opening Garry's Mod 12?
 - Is `steam_appid.txt` located next to `hl2.exe`?
